intersections:
- allowed_green_signal_combinations:
  - allowed:
    - N_STRAIGHT
    - S_STRAIGHT
    - W_RIGHT
    - W_LEFT
    signal: N_STRAIGHT_RIGHT
  - allowed:
    - S_STRAIGHT
    - N_STRAIGHT_RIGHT
    signal: N_STRAIGHT
  - allowed:
    - N_STRAIGHT
    - N_STRAIGHT_RIGHT
    signal: S_STRAIGHT
  - allowed:
    - W_LEFT
    signal: W_RIGHT
  - allowed:
    - W_RIGHT
    signal: W_LEFT
  amber_time: 3
  connections:
  - groups:
    - N_straight_right
    index: 0
    priority: true
  - groups:
    - N_straight
    index: 1
    priority: true
  - groups:
    - N_straight
    index: 2
    priority: true
  - groups:
    - N_straight
    index: 3
    priority: true
  - groups:
    - S_straight
    index: 4
    priority: true
  - groups:
    - S_straight
    index: 5
    priority: true
  - groups:
    - S_straight
    index: 6
    priority: true
  - groups:
    - W_right
    index: 7
    priority: true
  - groups:
    - W_left
    index: 8
    priority: true
  - groups:
    - W_left
    index: 9
    priority: true
  groups:
  - W_right
  - N_straight_right
  - W_left
  - S_straight
  - N_straight
  junction: intersection
  legs:
  - groups:
    - N_straight
    - N_straight_right
    lanes:
    - straight_right
    - straight
    - straight
    - straight
    name: N
    segments:
    - N_1
  - groups:
    - S_straight
    lanes:
    - straight
    - straight
    - straight
    name: S
    segments:
    - S_1
  - groups:
    - W_right
    - W_left
    lanes:
    - right
    - left
    - left
    name: W
    segments:
    - W_1
  red_amber_time: 0
