intersections:
- allowed_green_signal_combinations:
  - allowed:
    - S_RIGHT
    - S_STRAIGHT
    signal: N_STRAIGHT
  - allowed:
    - S_LEFT
    - S_STRAIGHT
    - N_STRAIGHT
    signal: S_RIGHT
  - allowed:
    - S_RIGHT
    - S_LEFT
    - N_STRAIGHT
    signal: S_STRAIGHT
  - allowed:
    - S_RIGHT
    - S_STRAIGHT
    signal: S_LEFT
  - allowed:
    - W_STRAIGHT
    - W_RIGHT
    signal: E_STRAIGHT
  - allowed:
    - W_STRAIGHT
    - E_STRAIGHT
    signal: W_RIGHT
  - allowed:
    - E_STRAIGHT
    - W_RIGHT
    signal: W_STRAIGHT
  amber_time: 3
  connections:
  - groups:
    - N_straight
    index: 0
    priority: true
  - groups:
    - N_straight
    index: 1
    priority: true
  - groups:
    - S_right
    index: 2
    priority: true
  - groups:
    - S_straight
    index: 3
    priority: true
  - groups:
    - S_straight
    index: 4
    priority: true
  - groups:
    - S_left
    index: 5
    priority: true
  - groups:
    - E_straight
    index: 6
    priority: true
  - groups:
    - E_straight
    index: 7
    priority: true
  - groups:
    - E_straight
    index: 8
    priority: true
  - groups:
    - W_right
    index: 9
    priority: true
  - groups:
    - W_straight
    index: 10
    priority: true
  - groups:
    - W_straight
    index: 11
    priority: true
  - groups:
    - W_straight
    index: 12
    priority: true
  - groups:
    - W_straight
    index: 13
    priority: true
  groups:
  - S_left
  - W_straight
  - N_straight
  - S_right
  - S_straight
  - W_right
  - E_straight
  junction: intersection
  legs:
  - groups:
    - N_straight
    lanes:
    - straight
    - straight
    name: N
    segments:
    - N_1
  - groups:
    - S_left
    - S_right
    - S_straight
    lanes:
    - right
    - straight
    - straight
    - left
    name: S
    segments:
    - S_1
  - groups:
    - E_straight
    lanes:
    - straight
    - straight
    - straight
    name: E
    segments:
    - E_1
  - groups:
    - W_straight
    - W_right
    lanes:
    - right
    - straight
    - straight
    - straight
    - straight
    name: W
    segments:
    - W_1
  red_amber_time: 0
