intersections:
- allowed_green_signal_combinations:
  - allowed: []
    signal: N_STRAIGHT
  - allowed: []
    signal: S_MAIN
  - allowed:
    - W_STRAIGHT
    - E_STRAIGHT
    - W_RIGHT
    signal: E_RIGHT
  - allowed:
    - W_STRAIGHT
    - E_RIGHT
    - W_RIGHT
    signal: E_STRAIGHT
  - allowed:
    - W_STRAIGHT
    - E_RIGHT
    - E_STRAIGHT
    - W_LEFT
    signal: W_RIGHT
  - allowed:
    - E_RIGHT
    - E_STRAIGHT
    - W_RIGHT
    - W_LEFT
    signal: W_STRAIGHT
  - allowed:
    - W_STRAIGHT
    - W_RIGHT
    signal: W_LEFT
  amber_time: 3
  connections:
  - groups:
    - N_straight
    index: 0
    priority: true
  - groups:
    - N_straight
    index: 1
    priority: true
  - groups:
    - N_straight
    index: 2
    priority: true
  - groups:
    - N_straight
    index: 3
    priority: true
  - groups:
    - E_right
    index: 7
    priority: true
  - groups:
    - E_right
    index: 8
    priority: true
  - groups:
    - E_straight
    index: 9
    priority: true
  - groups:
    - W_right
    index: 10
    priority: true
  - groups:
    - W_straight
    index: 11
    priority: true
  - groups:
    - W_left
    index: 12
    priority: true
  - groups:
    - W_left
    index: 13
    priority: true
  - groups:
    - W_left
    index: 14
    priority: true
  groups:
  - W_straight
  - N_straight
  - E_right
  - W_left
  - S_main
  - W_right
  - E_straight
  junction: intersection
  legs:
  - groups:
    - N_straight
    lanes:
    - straight
    - straight
    - straight
    - straight
    name: N
    segments:
    - N_1
  - groups:
    - S_main
    lanes:
    - main
    name: S
    segments:
    - S_1
  - groups:
    - E_right
    - E_straight
    lanes:
    - right
    - right
    - straight
    name: E
    segments:
    - E_1
  - groups:
    - W_straight
    - W_right
    - W_left
    lanes:
    - right
    - straight
    - left
    - left
    - left
    name: W
    segments:
    - W_1
  red_amber_time: 0
