intersections:
- allowed_green_signal_combinations:
  - allowed:
    - S_RIGHT
    - N_LEFT
    - S_STRAIGHT
    signal: N_STRAIGHT
  - allowed:
    - N_STRAIGHT
    signal: N_LEFT
  - allowed:
    - S_STRAIGHT
    - N_STRAIGHT
    signal: S_RIGHT
  - allowed:
    - S_RIGHT
    - N_STRAIGHT
    signal: S_STRAIGHT
  - allowed:
    - W_STRAIGHT
    - E_LEFT
    signal: E_STRAIGHT
  - allowed:
    - E_STRAIGHT
    signal: E_LEFT
  - allowed:
    - E_STRAIGHT
    signal: W_STRAIGHT
  amber_time: 3
  connections:
  - groups:
    - N_straight
    index: 0
    priority: true
  - groups:
    - N_left
    index: 1
    priority: true
  - groups:
    - S_right
    index: 2
    priority: true
  - groups:
    - S_straight
    index: 3
    priority: true
  - groups:
    - S_straight
    index: 4
    priority: true
  - groups:
    - S_straight
    index: 5
    priority: true
  - groups:
    - S_straight
    index: 6
    priority: true
  - groups:
    - E_straight
    index: 7
    priority: true
  - groups:
    - E_left
    index: 8
    priority: true
  - groups:
    - W_straight
    index: 9
    priority: true
  - groups:
    - W_straight
    index: 10
    priority: true
  - groups:
    - W_straight
    index: 11
    priority: true
  groups:
  - W_straight
  - N_left
  - E_left
  - N_straight
  - S_right
  - S_straight
  - E_straight
  junction: intersection
  legs:
  - groups:
    - N_straight
    - N_left
    lanes:
    - straight
    - left
    name: N
    segments:
    - N_1
  - groups:
    - S_right
    - S_straight
    lanes:
    - right
    - straight
    - straight
    - straight
    - straight
    name: S
    segments:
    - S_1
  - groups:
    - E_left
    - E_straight
    lanes:
    - straight
    - left
    name: E
    segments:
    - E_1
  - groups:
    - W_straight
    lanes:
    - straight
    - straight
    - straight
    name: W
    segments:
    - W_1
  red_amber_time: 0
