intersections:
  - allowed_green_signal_combinations:
      - allowed:
          - S_STRAIGHT
          - N_LEFT
        signal: N_STRAIGHT
      - allowed:
          - S_LEFT
          - N_STRAIGHT
        signal: N_LEFT
      - allowed:
          - S_LEFT
          - N_STRAIGHT
        signal: S_STRAIGHT
      - allowed:
          - S_STRAIGHT
          - N_LEFT
        signal: S_LEFT
      - allowed:
          - E_LEFT
          - W_STRAIGHT
        signal: E_STRAIGHT
      - allowed:
          - W_LEFT
          - E_STRAIGHT
        signal: E_LEFT
      - allowed:
          - W_LEFT
          - E_STRAIGHT
        signal: W_STRAIGHT
      - allowed:
          - E_LEFT
          - W_STRAIGHT
        signal: W_LEFT
    amber_time: 3
    connections:
      - groups:
          - N_STRAIGHT
        index: 0
        priority: true
      - groups:
          - N_STRAIGHT
        index: 1
        priority: true
      - groups:
          - N_LEFT
        index: 2
        priority: true
      - groups:
          - S_STRAIGHT
        index: 3
        priority: true
      - groups:
          - S_STRAIGHT
        index: 4
        priority: true
      - groups:
          - S_LEFT
        index: 5
        priority: true
      - groups:
          - E_STRAIGHT
        index: 6
        priority: true
      - groups:
          - E_STRAIGHT
        index: 7
        priority: true
      - groups:
          - E_LEFT
        index: 8
        priority: true
      - groups:
          - W_STRAIGHT
        index: 9
        priority: true
      - groups:
          - W_STRAIGHT
        index: 10
        priority: true
      - groups:
          - W_LEFT
        index: 11
        priority: true
      - groups:
          - W_LEFT
        index: 12
        priority: true
      - groups:
          - W_LEFT
        index: 13
        priority: true
    groups:
      - W_STRAIGHT
      - E_LEFT
      - E_STRAIGHT
      - N_STRAIGHT
      - S_LEFT
      - W_LEFT
      - S_STRAIGHT
      - N_LEFT
    junction: intersection
    legs:
      - groups:
          - N_LEFT
          - N_STRAIGHT
        lanes:
          - STRAIGHT
          - STRAIGHT
          - LEFT
        name: N_1
        segments:
          - N_1
      - groups:
          - S_STRAIGHT
          - S_LEFT
        lanes:
          - STRAIGHT
          - STRAIGHT
          - LEFT
        name: S_1
        segments:
          - S_1
      - groups:
          - E_LEFT
          - E_STRAIGHT
        lanes:
          - STRAIGHT
          - STRAIGHT
          - LEFT
        name: E_1
        segments:
          - E_1
      - groups:
          - W_STRAIGHT
          - W_LEFT
        lanes:
          - STRAIGHT
          - STRAIGHT
          - LEFT
          - LEFT
          - LEFT
        name: W_1
        segments:
          - W_1
    red_amber_time: 0
