intersections:
- allowed_green_signal_combinations:
  - allowed:
    - N_STRAIGHT
    signal: N_LEFT
  - allowed:
    - N_LEFT
    - S_STRAIGHT
    signal: N_STRAIGHT
  - allowed:
    - N_STRAIGHT
    signal: S_STRAIGHT
  - allowed: []
    signal: E_LEFT
  amber_time: 3
  connections:
  - groups:
    - N_left
    index: 0
    priority: true
  - groups:
    - N_straight
    index: 1
    priority: true
  - groups:
    - S_straight
    index: 2
    priority: true
  - groups:
    - S_straight
    index: 3
    priority: true
  - groups:
    - E_left
    index: 4
    priority: true
  groups:
  - N_straight
  - N_left
  - E_left
  - S_straight
  junction: intersection
  legs:
  - groups:
    - N_straight
    - N_left
    lanes:
    - left
    - straight
    name: N
    segments:
    - N_1
  - groups:
    - S_straight
    lanes:
    - straight
    - straight
    name: S
    segments:
    - S_1
  - groups:
    - E_left
    lanes:
    - left
    name: E
    segments:
    - E_1
  red_amber_time: 0
