intersections:
- allowed_green_signal_combinations:
  - allowed:
    - S_RIGHT
    - N_LEFT
    signal: N_RIGHT
  - allowed:
    - S_LEFT
    - N_RIGHT
    signal: N_LEFT
  - allowed:
    - S_LEFT
    - N_RIGHT
    signal: S_RIGHT
  - allowed:
    - S_RIGHT
    - N_LEFT
    signal: S_LEFT
  - allowed: []
    signal: E_MAIN
  - allowed:
    - W_LEFT
    signal: W_STRAIGHT
  - allowed:
    - W_STRAIGHT
    signal: W_LEFT
  amber_time: 3
  connections:
  - groups:
    - N_right
    index: 0
    priority: true
  - groups:
    - N_left
    index: 1
    priority: true
  - groups:
    - S_right
    index: 2
    priority: true
  - groups:
    - S_left
    index: 3
    priority: true
  - groups:
    - S_left
    index: 4
    priority: true
  - groups:
    - S_left
    index: 5
    priority: true
  - groups:
    - S_left
    index: 6
    priority: true
  - groups:
    - W_straight
    index: 10
    priority: true
  - groups:
    - W_straight
    index: 11
    priority: true
  - groups:
    - W_left
    index: 12
    priority: true
  - groups:
    - W_left
    index: 13
    priority: true
  groups:
  - S_left
  - W_straight
  - E_main
  - N_left
  - S_right
  - W_left
  - N_right
  junction: intersection
  legs:
  - groups:
    - N_right
    - N_left
    lanes:
    - right
    - left
    name: N
    segments:
    - N_1
  - groups:
    - S_left
    - S_right
    lanes:
    - right
    - left
    - left
    - left
    - left
    name: S
    segments:
    - S_1
  - groups:
    - E_main
    lanes:
    - main
    name: E
    segments:
    - E_1
  - groups:
    - W_straight
    - W_left
    lanes:
    - straight
    - straight
    - left
    - left
    name: W
    segments:
    - W_1
  red_amber_time: 0
