intersections:
- allowed_green_signal_combinations:
  - allowed:
    - S_STRAIGHT
    signal: N_STRAIGHT
  - allowed:
    - S_LEFT
    - N_STRAIGHT
    signal: S_STRAIGHT
  - allowed:
    - S_STRAIGHT
    signal: S_LEFT
  - allowed:
    - E_LEFT
    signal: E_STRAIGHT
  - allowed:
    - E_STRAIGHT
    signal: E_LEFT
  - allowed: []
    signal: W_MAIN
  amber_time: 3
  connections:
  - groups:
    - N_straight
    index: 0
    priority: true
  - groups:
    - S_straight
    index: 1
    priority: true
  - groups:
    - S_left
    index: 2
    priority: true
  - groups:
    - E_straight
    index: 3
    priority: true
  - groups:
    - E_straight
    index: 4
    priority: true
  - groups:
    - E_left
    index: 5
    priority: true
  - groups:
    - E_left
    index: 6
    priority: true
  groups:
  - S_left
  - W_main
  - E_left
  - N_straight
  - S_straight
  - E_straight
  junction: intersection
  legs:
  - groups:
    - N_straight
    lanes:
    - straight
    name: N
    segments:
    - N_1
  - groups:
    - S_left
    - S_straight
    lanes:
    - straight
    - left
    name: S
    segments:
    - S_1
  - groups:
    - E_left
    - E_straight
    lanes:
    - straight
    - straight
    - left
    - left
    name: E
    segments:
    - E_1
  - groups:
    - W_main
    lanes:
    - main
    name: W
    segments:
    - W_1
  red_amber_time: 0
