intersections:
- allowed_green_signal_combinations:
  - allowed:
    - S_RIGHT
    signal: S_LEFT
  - allowed:
    - S_LEFT
    signal: S_RIGHT
  - allowed:
    - W_STRAIGHT
    - E_LEFT
    - W_RIGHT
    signal: E_STRAIGHT
  - allowed:
    - E_STRAIGHT
    signal: E_LEFT
  - allowed:
    - W_STRAIGHT
    - E_STRAIGHT
    signal: W_RIGHT
  - allowed:
    - E_STRAIGHT
    - W_RIGHT
    signal: W_STRAIGHT
  amber_time: 3
  connections:
  - groups:
    - S_left
    index: 0
    priority: true
  - groups:
    - S_right
    index: 1
    priority: true
  - groups:
    - E_straight
    index: 2
    priority: true
  - groups:
    - E_straight
    index: 3
    priority: true
  - groups:
    - E_left
    index: 4
    priority: true
  - groups:
    - E_left
    index: 5
    priority: true
  - groups:
    - E_left
    index: 6
    priority: true
  - groups:
    - W_right
    index: 7
    priority: true
  - groups:
    - W_straight
    index: 8
    priority: true
  - groups:
    - W_straight
    index: 9
    priority: true
  - groups:
    - W_straight
    index: 10
    priority: true
  - groups:
    - W_straight
    index: 11
    priority: true
  groups:
  - S_left
  - W_straight
  - E_left
  - S_right
  - W_right
  - E_straight
  junction: intersection
  legs:
  - groups:
    - S_left
    - S_right
    lanes:
    - left
    - right
    name: S
    segments:
    - S_1
  - groups:
    - E_left
    - E_straight
    lanes:
    - straight
    - straight
    - left
    - left
    - left
    name: E
    segments:
    - E_1
  - groups:
    - W_straight
    - W_right
    lanes:
    - right
    - straight
    - straight
    - straight
    - straight
    name: W
    segments:
    - W_1
  red_amber_time: 0
