intersections:
- allowed_green_signal_combinations:
  - allowed:
    - S_STRAIGHT
    signal: N_STRAIGHT
  - allowed:
    - N_STRAIGHT
    signal: S_STRAIGHT
  - allowed: []
    signal: W_RIGHT
  amber_time: 3
  connections:
  - groups:
    - N_straight
    index: 0
    priority: true
  - groups:
    - N_straight
    index: 1
    priority: true
  - groups:
    - N_straight
    index: 2
    priority: true
  - groups:
    - S_straight
    index: 3
    priority: true
  - groups:
    - S_straight
    index: 4
    priority: true
  - groups:
    - W_right
    index: 5
    priority: true
  - groups:
    - W_right
    index: 6
    priority: true
  - groups:
    - W_right
    index: 7
    priority: true
  groups:
  - N_straight
  - W_right
  - S_straight
  junction: intersection
  legs:
  - groups:
    - N_straight
    lanes:
    - straight
    - straight
    - straight
    name: N
    segments:
    - N_1
  - groups:
    - S_straight
    lanes:
    - straight
    - straight
    name: S
    segments:
    - S_1
  - groups:
    - W_right
    lanes:
    - right
    - right
    - right
    name: W
    segments:
    - W_1
  red_amber_time: 0
