intersections:
  - x_offset: 295
    y_offset: 448
    box_system_host: "172.17.0.1"
    legs:
      - name: S
        lanes: [left, straight, straight]
        groups: [S, S_left]
        radar: R3
        segments: ["31552319#1"]
      - name: N
        lanes: [left, straight, straight]
        groups: [N, N_left]
        radar: R1
        segments: ["661830501", "661949705#2", "661949705#1"]
      - name: E
        lanes: [left, straight, straight]
        groups: [E, E_left]
        segments: ["661806767", "661806765", "31552288"]
        radar: R2
      - name: W
        lanes: [left, left, left, straight, straight]
        groups: [W, W_left]
        segments: ["661835697", "661830503#1-AddedOffRampEdge"]
        radar: R4
    radars:
      # R1 Cafe
      - port: 55556
        edges: ["661830501", "661949705#2", "661949705#1"]
        message_frequency: 20
        radar_range: 200
        name: R1
      # R2 Restaurant
      - port: 55557
        edges: ["661806767", "661806765", "31552288"]
        message_frequency: 20
        radar_range: 200
        name: R2
      # R3 Hotel
      - port: 55558
        edges: ["31552319#1"]
        message_frequency: 20
        radar_range: 200
        name: R3
        ats_name: "R3 Hotel"
      # R4 Factory
      - port: 55559
        edges: ["661835697", "661830503#1-AddedOffRampEdge"]
        message_frequency: 20
        radar_range: 200
    connections:
      #Factory lane #1
      - index: 0
        groups: [W]
        priority: true
      #Factory lane #2
      - index: 0
        groups: [W]
        priority: true
      #Factory_left #1
      - index: 1
        groups: [W_left]
        priority: true
      #Factory_left #2
      - index: 1
        groups: [W_left]
        priority: true
      #Factory_left #3
      - index: 1
        groups: [W_left]
        priority: true
      #Factory_left #4
      - index: 1
        groups: [W_left]
        priority: true
      #Factory_left #7
      - index: 1
        groups: [W_left]
        priority: true
      #Factory_left #8
      - index: 1
        groups: [W_left, N]
        priority: true
      #straight_road_Cafe #1
      - index: 3
        groups: [N]
        priority: true
      #straight_road_Cafe #2
      - index: 3
        groups: [N]
        priority: true
      #straight_left_Cafe #1
      - index: 4
        groups: [N_left]
        priority: true
      #straight_left_Cafe #2
      - index: 4
        groups: [N_left]
        priority: true
      #Restaurant #1
      - index: 5
        groups: [E]
        priority: true
      #Restaurant #2
      - index: 5
        groups: [E]
        priority: true
      #Restaurant left #1
      - index: 5
        groups: [E]
        priority: true
      #Restaurant left #2
      - index: 5
        groups: [E]
        priority: true
      #straight_road_Hotel #1
      - index: 6
        groups: [S]
        priority: true
      #straight_road_Hotel #2
      - index: 6
        groups: [S]
        priority: true
      #straight_left_Hotel #1
      - index: 7
        groups: [S_left]
        priority: true
      #straight_left_Hotel #2
      - index: 7
        groups: [S_left]
        priority: true
      # - index: 12
      #   groups: [N]
      #   priority: false
      # - index: 13
      #   groups: [bf]
      #   priority: true
      # - index: 14
      #   groups: [ag]
      #   priority: true
      # - index: 15
      #   groups: [bg]
      #   priority: true
      # - index: 16
      #   groups: [af]
      #   priority: true
    groups: [S, S_left, N, N_left, E, E_left, W, W_left]
    allowed_green_signal_combinations:
      - signal: [S]
        allowed: [S_left, N]
      - signal: [S_left]
        allowed: [S, N_left]
      - signal: [N]
        allowed: [N_left, S]
      - signal: [N_left]
        allowed: [N, S_left]
      - signal: [E]
        allowed: [E_left, W]
      - signal: [E_left]
        allowed: [E, W_left]
      - signal: [W]
        allowed: [W_left, E]
      - signal: [W_left]
        allowed: [W, E_left]
    red_green_only: []
    junction: cluster_248566141_248566148_5718595916_6196128282
    swarco_port: 2000
    amber_time: 3
    red_amber_time: 0
