intersections:
  - x_offset: 295
    y_offset: 448
    box_system_host: "172.17.0.1"
    legs:
      - name: A1
        lanes: [Left, Main, Main]
        groups: [A1, A1LeftTurn]
        radar: R3
        segments: ["A1"]
      - name: C1
        lanes: [Left, Main, Main]
        groups: [C1, C1LeftTurn]
        radar: R1
        segments: ["C1"]
      - name: B1
        lanes: [Left, Main, Main]
        groups: [B1, B1LeftTurn]
        segments: ["B1"]
        radar: R2
      - name: D1
        lanes: [Left, Left, Left, Main, Main]
        groups: [D1, D1LeftTurn]
        segments: ["D1"]
        radar: R4
    radars:
      # R1 Cafe
      - port: 55556
        edges: ["C1"]
        message_frequency: 20
        radar_range: 200
        name: R1
      # R2 Restaurant
      - port: 55557
        edges: ["B1"]
        message_frequency: 20
        radar_range: 200
        name: R2
      # R3 Hotel
      - port: 55558
        edges: ["A1"]
        message_frequency: 20
        radar_range: 200
        name: R3
        ats_name: "R3 Hotel"
      # R4 Factory
      - port: 55559
        edges: ["D1"]
        message_frequency: 20
        radar_range: 200
    connections:
      #Factory lane #1
      - index: 0
        groups: [D1]
        priority: true
      #Factory lane #2
      - index: 0
        groups: [D1]
        priority: true
      #Factory_left #1
      - index: 1
        groups: [D1LeftTurn]
        priority: true
      #Factory_left #2
      - index: 1
        groups: [D1LeftTurn]
        priority: true
      #Factory_left #3
      - index: 1
        groups: [D1LeftTurn]
        priority: true
      #Factory_left #4
      - index: 1
        groups: [D1LeftTurn]
        priority: true
      #Factory_left #7
      - index: 1
        groups: [D1LeftTurn]
        priority: true
      #Factory_left #8
      - index: 1
        groups: [D1LeftTurn, C1]
        priority: true
      #Main_road_Cafe #1
      - index: 3
        groups: [C1]
        priority: true
      #Main_road_Cafe #2
      - index: 3
        groups: [C1]
        priority: true
      #Main_left_Cafe #1
      - index: 4
        groups: [C1LeftTurn]
        priority: true
      #Main_left_Cafe #2
      - index: 4
        groups: [C1LeftTurn]
        priority: true
      #Restaurant #1
      - index: 5
        groups: [B1]
        priority: true
      #Restaurant #2
      - index: 5
        groups: [B1]
        priority: true
      #Restaurant left #1
      - index: 5
        groups: [B1]
        priority: true
      #Restaurant left #2
      - index: 5
        groups: [B1]
        priority: true
      #Main_road_Hotel #1
      - index: 6
        groups: [A1]
        priority: true
      #Main_road_Hotel #2
      - index: 6
        groups: [A1]
        priority: true
      #Main_left_Hotel #1
      - index: 7
        groups: [A1LeftTurn]
        priority: true
      #Main_left_Hotel #2
      - index: 7
        groups: [A1LeftTurn]
        priority: true
      # - index: 12
      #   groups: [C1]
      #   priority: false
      # - index: 13
      #   groups: [bf]
      #   priority: true
      # - index: 14
      #   groups: [ag]
      #   priority: true
      # - index: 15
      #   groups: [bg]
      #   priority: true
      # - index: 16
      #   groups: [af]
      #   priority: true
    groups: [A1, A1LeftTurn, C1, C1LeftTurn, B1, B1LeftTurn, D1, D1LeftTurn]
    allowed_green_signal_combinations:
      - signal: [A1]
        allowed: [A1LeftTurn, C1]
      - signal: [A1LeftTurn]
        allowed: [A1, C1LeftTurn]
      - signal: [C1]
        allowed: [C1LeftTurn, A1]
      - signal: [C1LeftTurn]
        allowed: [C1, A1LeftTurn]
      - signal: [B1]
        allowed: [B1LeftTurn, D1]
      - signal: [B1LeftTurn]
        allowed: [B1, D1LeftTurn]
      - signal: [D1]
        allowed: [D1LeftTurn, B1]
      - signal: [D1LeftTurn]
        allowed: [D1, B1LeftTurn]
    red_green_only: []
    junction: intersection
    swarco_port: 2000
    amber_time: 3
    red_amber_time: 0
