intersections:
- allowed_green_signal_combinations:
  - allowed:
    - N_RIGHT
    signal: N_LEFT
  - allowed:
    - N_LEFT
    signal: N_RIGHT
  - allowed:
    - W_STRAIGHT
    signal: E_STRAIGHT
  - allowed:
    - E_STRAIGHT
    signal: W_STRAIGHT
  amber_time: 3
  connections:
  - groups:
    - N_left
    index: 0
    priority: true
  - groups:
    - N_right
    index: 1
    priority: true
  - groups:
    - E_straight
    index: 2
    priority: true
  - groups:
    - E_straight
    index: 3
    priority: true
  - groups:
    - W_straight
    index: 4
    priority: true
  - groups:
    - W_straight
    index: 5
    priority: true
  groups:
  - N_right
  - W_straight
  - N_left
  - E_straight
  junction: intersection
  legs:
  - groups:
    - N_right
    - N_left
    lanes:
    - left
    - right
    name: N
    segments:
    - N_1
  - groups:
    - E_straight
    lanes:
    - straight
    - straight
    name: E
    segments:
    - E_1
  - groups:
    - W_straight
    lanes:
    - straight
    - straight
    name: W
    segments:
    - W_1
  red_amber_time: 0
